### ISSUE TITLE
No trips?

### ISSUE THREAD

**Issue by kafitz** [TRIP-Lab/itinerum-datakit#2]
_From @Nate-Wessel on February 11, 2018 16:43_

When running the tripbreaker for a user, I get the following error:

````
Writing trips for 44b9444a-ccb8-426b-878b-8b09318348e5 to database...
Traceback (most recent call last):
  File "run_tripbreaker/run_tripbreaker_on_user.py", line 370, in <module>
    run()
  File "run_tripbreaker/run_tripbreaker_on_user.py", line 349, in run
    write_trips_to_postgis(trips, summaries)
  File "run_tripbreaker/run_tripbreaker_on_user.py", line 87, in write_trips_to_postgis
    for trip_id, trip in trips.items():
AttributeError: 'NoneType' object has no attribute 'items'
````
(The line numbers may be slightly different. I tidied up the imports at the top of the script, without changing anything.)

It looks like no trips were found and there's nothing to write? One thing that could be an issue is that I'm not confident that my input CSV files have exactly the same schema as the ones output from the Itinerum website. It would be good to define this somewhere in the documentation. In my case, there have been some preprocessing steps and I'm not sure if I now have more or fewer fields now than I started with or if they all have the same names. Some checking during the DB import process could be called for. 

When I try running the tripbreaker on the whole survey, the script finishes immediately without errors and all the output tables are created, but they're empty. 

I haven't yet changed any tripbreaker parameters from the default - just the necessary configuration bits. 

_Copied from original issue: TRIP-Lab/itinerum-tripbreaker#2_

**Comment by kafitz** [comment]
@Nate-Wessel That would be correct that it's failing because no trips were detected and I'd only tested "run_tripbreaker_on_user.py" on users with successfully detected trips. I updated the user runner to behave the same way as the survey runner (and not fail when no trips are found), which will copy the tested user's coordinates & prompts to the output DB and the detected_trips table will be blank.

When I load in UofT data from scratch, however, this particular user has 80 detected trip events total so something else is going on. My first question would be whether the .sqlite source database is generating correctly from the input .csv files. Each table should look exactly like its respective input .csv (i.e., coordinates, survey_responses, prompt_responses) with the same number of rows and columns. If this all seems correct, the next check would likely be to see whether the point's lat/lon are reprojecting to UTM correctly in the first step of algorithm.py.

I agree this repository would benefit from input and unit testing, I'd recommend we create a /tests directory and first thing will be to make sure this input data is processed as expected (more of a To Do for myself there). It's original purpose was to share the tripbreaker's steps with the city but it may make sense to have it developed independent of the web platform. The supplied "runner" scripts were added as a quick demo wrapper for the algorithm.py file but you can let me know improvements you'd like to see to make it more useful as a generalized CLI tool.

**Comment by kafitz** [comment]
_From @Nate-Wessel on February 12, 2018 18:44_

I found the problem! 

Line 27 of either script 
````
'in_db_uri': 'sqlite:///../data/{s}-processing-{d}.sqlite'.format(s=SURVEY_NAME,
````
uses a relative URL and depends on the script being called from the same directory. I was calling python from one directory down though and it wasn't finding any database there. The real problem is just that this didn't throw any errors, e.g. "database not found".

**Comment by kafitz** [comment]
_From @Nate-Wessel on February 12, 2018 19:35_

So, I got the script working with the data exactly as you sent it, but when I cleaned up the input data, removing about half the points and some of the users, I once again get no trips, either from the user mentioned above (me, actually) or from anyone else. 

One thing I noticed that changed slightly is the format of the timestamp field. How does your script handle this? I see values like `2017-06-26T04:17:33-04:00` in the data you sent me, and my database is outputing values like `2017-06-21 16:36:21`, without the timezone and without that `T` in the middle. Could this be the source of this problem? Again, I'm getting no error messages; the script is just silently yielding no trips. 

The only real cleaning I've done at this point, to keep things very simple, is to clip our data to the seven day survey period and remove a small portion of points that were clear positional errors.

**Comment by kafitz** [comment]
**Regarding issue 1:**
Interesting, out of habit I always call my Python scripts from the same directory so I didn't see that one coming. I agree having a relative path there isn't great practice so I will look to fix that with my issue #3.

**Regarding 2:**
I wrestled with datetimes a lot in the beginning of this project initially having everything timezone unaware like how yours is outputting. I eventually converted everything to the ISO8601 standard (https://en.wikipedia.org/wiki/ISO_8601) when it became necessary to support different regions and crucially to account for changes in Daylight Savings during data collection. This is also why I import that special ISO8601 library instead of the basic Datetime, just so I don't have to worry about the conversion between the date objects and .csv strings.

When I test ciso8601.parse_datetime('2017-06-21 16:36:21'), I still receive a Python datetime object so it's difficult to say whether this is the exact reason, but I would recommend making this consistent and timezone aware. Unfortunately, not a lot of the platform users are aware of the nuances of dealing with timestamps and so I had been trying to localize this via the platform export until now. The two options in such a situation for storing the data is converting everything to UTC, Unix integer "epoch" time (which I figured would confuse users even more) or storing the more verbose timezone-aware datetime.

**Next ideas to diagnose this:**
Can you add some debug print statements around line 62 of the algorithm https://github.com/TRIP-Lab/itinerum-tripbreaker/blob/b314d1fb359e85b981c71ff37d93473f65c6a8c5/run_tripbreaker/tripbreaker/algorithm.py#L62 to check that the seconds difference between each point seems accurate? 

I would also suggest line-by-line printing the len() of each variable generated in the run() function at the bottom of algorithm.py. That would really show how the data is being sent (or mysteriously dropped) between each step. I will send my input .sqlite db via email for comparison.

**Comment by kafitz** [comment]
@Nate-Wessel I just realized that the runner script was breaking yesterday when trips were returned as None. This should only happen when the tools.process_utm() function in run() does not return any points to process. This is the first function to debug, we should comment out the try/except portion here https://github.com/TRIP-Lab/itinerum-tripbreaker/blob/b314d1fb359e85b981c71ff37d93473f65c6a8c5/run_tripbreaker/tripbreaker/modules/tools.py#L30-L43 and see why it's giving a utm.error.OutOfRangeError error.

**Comment by kafitz** [comment]
_From @Nate-Wessel on February 13, 2018 16:59_

I tried inserting a few print statements as you suggested and found that I wasn't actually getting any points at all out of the database. It seems I had a `uid` column where I should have had `uuid`. The script seems for now to be working as expected, but I might again suggest that you try and make things a little less error tolerant. I'm not familiar with SQLalchemy, but it seems like it should throw a warning at least if you try to filter by a column that doesn't exist in the database. Possibly this is related to [line 17 and 18](https://github.com/TRIP-Lab/itinerum-tripbreaker/blob/master/run_tripbreaker/run_tripbreaker_on_user.py#L17)?

Thanks for your help on this!

**Comment by kafitz** [comment]
Continued discussion on input sanitization #6
